/* eslint-disable quotes */
/* eslint-disable quote-props */
const Owners = [
  {
    "fullName": "Laura Alexander",
    "ownerId": 34495882,
    "email": "lalexander@jonessign.com",
    "firstName": "Laura",
    "lastName": "Alexander",
  },
  {
    "fullName": "Ryan Barkby",
    "ownerId": 30687834,
    "email": "rbarkby@jonessign.com",
    "firstName": "Ryan",
    "lastName": "Barkby",
  },
  {
    "fullName": "Patrick Basche",
    "ownerId": 31204197,
    "email": "pbasche@jonessign.com",
    "firstName": "Patrick",
    "lastName": "Basche",
  },
  {
    "fullName": "Steve Berryman",
    "ownerId": 30916772,
    "email": "sberryman@jonessign.com",
    "firstName": "Steve",
    "lastName": "Berryman",
  },
  {
    "fullName": "Michael Bjorklund",
    "ownerId": 30916845,
    "email": "mbjorklund@jonessign.com",
    "firstName": "Michael",
    "lastName": "Bjorklund",
  },
  {
    "fullName": "Jason Boccard",
    "ownerId": 33251080,
    "email": "jboccard@jonessign.com",
    "firstName": "Jason",
    "lastName": "Boccard",
  },
  {
    "fullName": "Rick Campbell",
    "ownerId": 31203644,
    "email": "rcampbell@jonessign.com",
    "firstName": "Rick",
    "lastName": "Campbell",
  },
  {
    "fullName": "Jeff Crowell",
    "ownerId": 31203639,
    "email": "jcrowell@jonessign.com",
    "firstName": "Jeff",
    "lastName": "Crowell",
  },
  {
    "fullName": "Katie De La Rosa",
    "ownerId": 35892833,
    "email": "kdelarosa@jonessign.com",
    "firstName": "Katie",
    "lastName": "De La Rosa",
  },
  {
    "fullName": "Rob Fought",
    "ownerId": 31204178,
    "email": "rfought@jonessign.com",
    "firstName": "Rob",
    "lastName": "Fought",
  },
  {
    "fullName": "Dick Frank",
    "ownerId": 32650400,
    "email": "dfrank@jonessign.com",
    "firstName": "Dick",
    "lastName": "Frank",
  },
  {
    "fullName": "Jennifer Galvin",
    "ownerId": 31203600,
    "email": "jgalvin@jonessign.com",
    "firstName": "Jennifer",
    "lastName": "Galvin",
  },
  {
    "fullName": "Jared Gehrt",
    "ownerId": 32643329,
    "email": "jgehrt@jonessign.com",
    "firstName": "Jared",
    "lastName": "Gehrt",
  },
  {
    "fullName": "Charles Godinez",
    "ownerId": 33339116,
    "email": "cgodinez@jonessign.com",
    "firstName": "Charles",
    "lastName": "Godinez",
  },
  {
    "fullName": "Cori Golden",
    "ownerId": 32186441,
    "email": "cgolden@jonessign.com",
    "firstName": "Cori",
    "lastName": "Golden",
  },
  {
    "fullName": "Ellen Groff",
    "ownerId": 31538047,
    "email": "egroff@jonessign.com",
    "firstName": "Ellen",
    "lastName": "Groff",
  },
  {
    "fullName": "Mike Hager",
    "ownerId": 32650431,
    "email": "mhager@jonessign.com",
    "firstName": "Mike",
    "lastName": "Hager",
  },
  {
    "fullName": "Dave Heideman",
    "ownerId": 31203632,
    "email": "dheideman@jonessign.com",
    "firstName": "Dave",
    "lastName": "Heideman",
  },
  {
    "fullName": "Rich Hinshaw",
    "ownerId": 31203594,
    "email": "rhinshaw@jonessign.com",
    "firstName": "Rich",
    "lastName": "Hinshaw",
  },
  {
    "fullName": "Steve Hirtz",
    "ownerId": 32675032,
    "email": "shirtz@jonessign.com",
    "firstName": "Steve",
    "lastName": "Hirtz",
  },
  {
    "fullName": "Ron Hunter",
    "ownerId": 33993669,
    "email": "rhunter@jonessign.com",
    "firstName": "Ron",
    "lastName": "Hunter",
  },
  {
    "fullName": "Jon Jasper",
    "ownerId": 35675006,
    "email": "jjasper@jonessign.com",
    "firstName": "Jon",
    "lastName": "Jasper",
  },
  {
    "fullName": "Terry Kasarsky",
    "ownerId": 31301461,
    "email": "tkasarsky@jonessign.com",
    "firstName": "Terry",
    "lastName": "Kasarsky",
  },
  {
    "fullName": "Kristopher Kay",
    "ownerId": 31203583,
    "email": "kkay@jonessign.com",
    "firstName": "Kristopher",
    "lastName": "Kay",
  },
  {
    "fullName": "Martin Kindred",
    "ownerId": 35497342,
    "email": "mkindred@jonessign.com",
    "firstName": "Martin",
    "lastName": "Kindred",
  },
  {
    "fullName": "Troy Korthour",
    "ownerId": 31885694,
    "email": "tkorthour@jonessign.com",
    "firstName": "Troy",
    "lastName": "Korthour",
  },
  {
    "fullName": "Donna La Crosse",
    "ownerId": 32197529,
    "email": "dlacrosse@jonessign.com",
    "firstName": "Donna",
    "lastName": "La Crosse",
  },
  {
    "fullName": "Sara Ledvina",
    "ownerId": 31538044,
    "email": "sledvina@jonessign.com",
    "firstName": "Sara",
    "lastName": "Ledvina",
  },
  {
    "fullName": "Nick Lison",
    "ownerId": 31203648,
    "email": "nlison@jonessign.com",
    "firstName": "Nick",
    "lastName": "Lison",
  },
  {
    "fullName": "Nellie McDermott",
    "ownerId": 31203395,
    "email": "nmcdermott@jonessign.com",
    "firstName": "Nellie",
    "lastName": "McDermott",
  },
  {
    "fullName": "Jimmy McDonald",
    "ownerId": 31203573,
    "email": "jmcdonald@jonessign.com",
    "firstName": "Jimmy",
    "lastName": "McDonald",
  },
  {
    "fullName": "Jim Merriman",
    "ownerId": 30916823,
    "email": "jmerriman@jonessign.com",
    "firstName": "Jim",
    "lastName": "Merriman",
  },
  {
    "fullName": "Al Mikula",
    "ownerId": 32437982,
    "email": "amikula@jonessign.com",
    "firstName": "Al",
    "lastName": "Mikula",
  },
  {
    "fullName": "Kevin Morris",
    "ownerId": 31204221,
    "email": "kmorris@jonessign.com",
    "firstName": "Kevin",
    "lastName": "Morris",
  },
  {
    "fullName": "Nick Mortensen",
    "ownerId": 31472372,
    "email": "nmortensen@jonessign.com",
    "firstName": "Nick",
    "lastName": "Mortensen",
  },
  {
    "fullName": "John Mortensen",
    "ownerId": 31755832,
    "email": "jmortensen@jonessign.com",
    "firstName": "John",
    "lastName": "Mortensen",
  },
  {
    "fullName": "Bill O'Gorman",
    "ownerId": 32645290,
    "email": "bogorman@jonessign.com",
    "firstName": "Bill",
    "lastName": "O'Gorman",
  },
  {
    "fullName": "Mimi Olson",
    "ownerId": 32439387,
    "email": "molson@jonessign.com",
    "firstName": "Mimi",
    "lastName": "Olson",
  },
  {
    "fullName": "Rich Ongirski",
    "ownerId": 30746762,
    "email": "rongirski@jonessign.com",
    "firstName": "Rich",
    "lastName": "Ongirski",
  },
  {
    "fullName": "Taylor Parrish",
    "ownerId": 34637231,
    "email": "tparrish@jonessign.com",
    "firstName": "Taylor",
    "lastName": "Parrish",
  },
  {
    "fullName": "Todd Patrickus",
    "ownerId": 30919668,
    "email": "tpatrickus@jonessign.com",
    "firstName": "Todd",
    "lastName": "Patrickus",
  },
  {
    "fullName": "Dave Peltier",
    "ownerId": 32660365,
    "email": "dpeltier@jonessign.com",
    "firstName": "Dave",
    "lastName": "Peltier",
  },
  {
    "fullName": "Jason Poland",
    "ownerId": 32650693,
    "email": "jpoland@jonessign.com",
    "firstName": "Jason",
    "lastName": "Poland",
  },
  {
    "fullName": "Christina Price",
    "ownerId": 31204217,
    "email": "cprice@jonessign.com",
    "firstName": "Christina",
    "lastName": "Price",
  },
  {
    "fullName": "Darcy Quigley",
    "ownerId": 34033740,
    "email": "dquigley@jonessign.com",
    "firstName": "Darcy",
    "lastName": "Quigley",
  },
  {
    "fullName": "Bill Reicherter",
    "ownerId": 34379442,
    "email": "breicherter@jonessign.com",
    "firstName": "Bill",
    "lastName": "Reicherter",
  },
  {
    "fullName": "Bob Russell",
    "ownerId": 31283436,
    "email": "brussell@jonessign.com",
    "firstName": "Bob",
    "lastName": "Russell",
  },
  {
    "fullName": "Steve Rutkowski",
    "ownerId": 32702574,
    "email": "srutkowski@jonessign.com",
    "firstName": "Steve",
    "lastName": "Rutkowski",
  },
  {
    "fullName": "Dikran Vartan",
    "ownerId": 31202615,
    "email": "dvartan@jonessign.com",
    "firstName": "Dikran",
    "lastName": "Vartan",
  },
  {
    "fullName": "Patrick Vaughan",
    "ownerId": 35383540,
    "email": "pvaughan@jonessign.com",
    "firstName": "Patrick",
    "lastName": "Vaughan",
  },
  {
    "fullName": "Mike Waich",
    "ownerId": 32675057,
    "email": "mwaich@jonessign.com",
    "firstName": "Mike",
    "lastName": "Waich",
  },
  {
    "fullName": "Robb Walker",
    "ownerId": 32168875,
    "email": "rwalker@jonessign.com",
    "firstName": "Robb",
    "lastName": "Walker",
  },
  {
    "fullName": "Laurel Walker",
    "ownerId": 32871452,
    "email": "lwalker@jonessign.com",
    "firstName": "Laurel",
    "lastName": "Walker",
  },
  {
    "fullName": "Lisa Waterfield",
    "ownerId": 35856837,
    "email": "lwaterfield@jonessign.com",
    "firstName": "Lisa",
    "lastName": "Waterfield",
  },
  {
    "fullName": "Natasha Wishart",
    "ownerId": 35892547,
    "email": "nwishart@jonessign.com",
    "firstName": "Natasha",
    "lastName": "Wishart",
  },
  {
    "fullName": "Jerry Zemanski",
    "ownerId": 32265164,
    "email": "jzemanski@jonessign.com",
    "firstName": "Jerry",
    "lastName": "Zemanski",
  },
];
